apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dataviz-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongodb-service 27017; do echo Initilaizing backend...; sleep 2; done;']
      containers:
        - name: backend
          image: ismailza/mern-stack-app-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/mydb
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
            - name: MONGO_URL
          envFROM:
           - configMapRef:
               name: backend-config
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log
        - name: sidecar
          image: busybox
          command: ['sh', '-c', 'tail -f /var/log/backend.log', sleep 5]
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
