apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-pv
  namespace: dataviz-ns
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/nginx/html
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard 
