apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173       
      targetPort: 80   
      nodePort: 30173  
