apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: dataviz-ns
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard 
